export type LawSchoolOption = {
  name: string;
  logo?: string;
};

export const LAW_SCHOOL_OPTIONS: LawSchoolOption[] = [
  { name: "Akron" },
  { name: "Alabama" },
  { name: "Albany" },
  { name: "American" },
  { name: "Appalachian" },
  { name: "Arizona" },
  { name: "Arizona State" },
  { name: "Arkansas – Fayetteville" },
  { name: "Arkansas – Little Rock" },
  { name: "Atlanta's John Marshall Law School" },
  { name: "Ave Maria School of Law" },
  { name: "Baltimore" },
  { name: "Barry University" },
  { name: "Baylor" },
  { name: "Belmont University" },
  { name: "Boston College" },
  { name: "Boston University" },
  { name: "Brigham Young" },
  { name: "Brooklyn" },
  { name: "Buffalo" },
  { name: "California – Berkeley" },
  { name: "California – Davis" },
  { name: "California – San Francisco" },
  { name: "California – Irvine" },
  { name: "California – Los Angeles (UCLA)", logo: "" },
  { name: "California Western" },
  { name: "Campbell" },
  { name: "Capital" },
  { name: "Case Western Reserve" },
  { name: "Catholic University of America" },
  { name: "Chapman" },
  { name: "Charleston" },
  { name: "Chicago" },
  { name: "Chicago-Kent" },
  { name: "Cincinnati" },
  { name: "City University of New York" },
  { name: "Cleveland State" },
  { name: "Colorado" },
  { name: "Columbia" },
  { name: "Connecticut" },
  { name: "Cooley Law School" },
  { name: "Cornell" },
  { name: "Creighton" },
  { name: "Dayton" },
  { name: "Denver" },
  { name: "DePaul" },
  { name: "Detroit Mercy" },
  { name: "District of Columbia (UDC)" },
  { name: "Drake" },
  { name: "Drexel" },
  { name: "Duke" },
  { name: "Duquesne" },
  { name: "Elon" },
  { name: "Emory" },
  { name: "Faulkner" },
  { name: "Florida" },
  { name: "Florida A&M" },
  { name: "Florida International" },
  { name: "Florida State" },
  { name: "Fordham" },
  { name: "George Mason" },
  { name: "Georgetown" },
  { name: "George Washington" },
  { name: "Georgia" },
  { name: "Georgia State" },
  { name: "Gonzaga" },
  { name: "Harvard" },
  { name: "Hawaii" },
  { name: "Hofstra" },
  { name: "Houston" },
  { name: "Howard" },
  { name: "Idaho" },
  { name: "Illinois Chicago" },
  { name: "Illinois" },
  { name: "Indiana University – Bloomington" },
  { name: "Indiana University – Indianapolis" },
  { name: "Iowa" },
  { name: "Kansas" },
  { name: "Kentucky" },
  { name: "Lewis and Clark" },
  { name: "Liberty" },
  { name: "Lincoln Memorial" },
  { name: "Louisiana State" },
  { name: "Louisville" },
  { name: "Loyola – Chicago" },
  { name: "Loyola – Los Angeles" },
  { name: "Loyola – New Orleans" },
  { name: "Maine" },
  { name: "Marquette" },
  { name: "Maryland" },
  { name: "Massachusetts" },
  { name: "McGeorge" },
  { name: "Memphis" },
  { name: "Mercer" },
  { name: "Miami" },
  { name: "Michigan State" },
  { name: "Michigan" },
  { name: "Minnesota" },
  { name: "Mississippi College" },
  { name: "Mississippi" },
  { name: "Missouri" },
  { name: "Missouri – Kansas City" },
  { name: "Mitchell Hamline" },
  { name: "Montana" },
  { name: "Nebraska" },
  { name: "Nevada" },
  { name: "New England Law | Boston" },
  { name: "New Hampshire" },
  { name: "New Mexico" },
  { name: "New York Law School" },
  { name: "New York University" },
  { name: "North Carolina" },
  { name: "North Carolina Central" },
  { name: "North Dakota" },
  { name: "Northeastern" },
  { name: "Northern Illinois" },
  { name: "Northern Kentucky" },
  { name: "Northwestern" },
  { name: "Notre Dame" },
  { name: "Nova Southeastern" },
  { name: "Ohio Northern" },
  { name: "The Ohio State" },
  { name: "Oklahoma" },
  { name: "Oklahoma City" },
  { name: "Oregon" },
  { name: "Pace" },
  { name: "Pennsylvania" },
  { name: "Penn State Dickinson" },
  { name: "Pepperdine" },
  { name: "Pittsburgh" },
  { name: "Pontifical Catholic of Puerto Rico" },
  { name: "Puerto Rico" },
  { name: "Quinnipiac" },
  { name: "Regent" },
  { name: "Richmond" },
  { name: "Roger Williams" },
  { name: "Rutgers" },
  { name: "St. John's" },
  { name: "Saint Louis" },
  { name: "St. Mary's" },
  { name: "St. Thomas (FL)" },
  { name: "St. Thomas (MN)" },
  { name: "Samford" },
  { name: "San Diego" },
  { name: "San Francisco" },
  { name: "Santa Clara" },
  { name: "Seattle" },
  { name: "Seton Hall" },
  { name: "South Carolina" },
  { name: "South Dakota" },
  { name: "South Texas-Houston" },
  { name: "Southern University" },
  { name: "Southern California" },
  { name: "Southern Illinois" },
  { name: "Southern Methodist" },
  { name: "Southwestern" },
  { name: "Stanford" },
  { name: "Stetson" },
  { name: "Suffolk" },
  { name: "Syracuse" },
  { name: "Temple" },
  { name: "Tennessee" },
  { name: "Texas" },
  { name: "Texas A&M" },
  { name: "Texas Southern" },
  { name: "Texas Tech" },
  { name: "Toledo" },
  { name: "Touro" },
  { name: "Tulane" },
  { name: "Tulsa" },
  { name: "UNT Dallas" },
  { name: "Utah" },
  { name: "Vanderbilt" },
  { name: "Vermont" },
  { name: "Villanova" },
  { name: "Virginia" },
  { name: "Wake Forest" },
  { name: "Washburn" },
  { name: "Washington and Lee" },
  { name: "Washington" },
  { name: "Washington University" },
  { name: "Wayne State" },
  { name: "Western New England" },
  { name: "Western State" },
  { name: "West Virginia" },
  { name: "Widener – Delaware" },
  { name: "Widener – Commonwealth" },
  { name: "Willamette" },
  { name: "William and Mary" },
  { name: "Wisconsin" },
  { name: "Wyoming" },
  { name: "Yale" },
  { name: "Yeshiva (Cardozo)" },
];

export const ABA_LAW_SCHOOLS = LAW_SCHOOL_OPTIONS.map((school) => school.name);

export const LAW_SCHOOL_LOGO_MAP = LAW_SCHOOL_OPTIONS.reduce<Record<string, string | undefined>>((acc, school) => {
  acc[school.name] = school.logo;
  return acc;
}, {});

export const getLawSchoolLogo = (name?: string | null) => (name ? LAW_SCHOOL_LOGO_MAP[name] : undefined);
