export const ABA_LAW_SCHOOLS = [
  "Akron",
  "Alabama",
  "Albany",
  "American",
  "Appalachian",
  "Arizona",
  "Arizona State",
  "Arkansas – Fayetteville",
  "Arkansas – Little Rock",
  "Atlanta's John Marshall Law School",
  "Ave Maria School of Law",
  "Baltimore",
  "Barry University",
  "Baylor",
  "Belmont University",
  "Boston College",
  "Boston University",
  "Brigham Young",
  "Brooklyn",
  "Buffalo",
  "California – Berkeley",
  "California – Davis",
  "California – San Francisco",
  "California – Irvine",
  "California – Los Angeles (UCLA)",
  "California Western",
  "Campbell",
  "Capital",
  "Case Western Reserve",
  "Catholic University of America",
  "Chapman",
  "Charleston",
  "Chicago",
  "Chicago-Kent",
  "Cincinnati",
  "City University of New York",
  "Cleveland State",
  "Colorado",
  "Columbia",
  "Connecticut",
  "Cooley Law School",
  "Cornell",
  "Creighton",
  "Dayton",
  "Denver",
  "DePaul",
  "Detroit Mercy",
  "District of Columbia (UDC)",
  "Drake",
  "Drexel",
  "Duke",
  "Duquesne",
  "Elon",
  "Emory",
  "Faulkner",
  "Florida",
  "Florida A&M",
  "Florida International",
  "Florida State",
  "Fordham",
  "George Mason",
  "Georgetown",
  "George Washington",
  "Georgia",
  "Georgia State",
  "Gonzaga",
  "Harvard",
  "Hawaii",
  "Hofstra",
  "Houston",
  "Howard",
  "Idaho",
  "Illinois Chicago",
  "Illinois",
  "Indiana University – Bloomington",
  "Indiana University – Indianapolis",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Lewis and Clark",
  "Liberty",
  "Lincoln Memorial",
  "Louisiana State",
  "Louisville",
  "Loyola – Chicago",
  "Loyola – Los Angeles",
  "Loyola – New Orleans",
  "Maine",
  "Marquette",
  "Maryland",
  "Massachusetts",
  "McGeorge",
  "Memphis",
  "Mercer",
  "Miami",
  "Michigan State",
  "Michigan",
  "Minnesota",
  "Mississippi College",
  "Mississippi",
  "Missouri",
  "Missouri – Kansas City",
  "Mitchell Hamline",
  "Montana",
  "Nebraska",
  "Nevada",
  "New England Law | Boston",
  "New Hampshire",
  "New Mexico",
  "New York Law School",
  "New York University",
  "North Carolina",
  "North Carolina Central",
  "North Dakota",
  "Northeastern",
  "Northern Illinois",
  "Northern Kentucky",
  "Northwestern",
  "Notre Dame",
  "Nova Southeastern",
  "Ohio Northern",
  "The Ohio State",
  "Oklahoma",
  "Oklahoma City",
  "Oregon",
  "Pace",
  "Pennsylvania",
  "Penn State Dickinson",
  "Pepperdine",
  "Pittsburgh",
  "Pontifical Catholic of Puerto Rico",
  "Puerto Rico",
  "Quinnipiac",
  "Regent",
  "Richmond",
  "Roger Williams",
  "Rutgers",
  "St. John's",
  "Saint Louis",
  "St. Mary's",
  "St. Thomas (FL)",
  "St. Thomas (MN)",
  "Samford",
  "San Diego",
  "San Francisco",
  "Santa Clara",
  "Seattle",
  "Seton Hall",
  "South Carolina",
  "South Dakota",
  "South Texas-Houston",
  "Southern University",
  "Southern California",
  "Southern Illinois",
  "Southern Methodist",
  "Southwestern",
  "Stanford",
  "Stetson",
  "Suffolk",
  "Syracuse",
  "Temple",
  "Tennessee",
  "Texas",
  "Texas A&M",
  "Texas Southern",
  "Texas Tech",
  "Toledo",
  "Touro",
  "Tulane",
  "Tulsa",
  "UNT Dallas",
  "Utah",
  "Vanderbilt",
  "Vermont",
  "Villanova",
  "Virginia",
  "Wake Forest",
  "Washburn",
  "Washington and Lee",
  "Washington",
  "Washington University",
  "Wayne State",
  "Western New England",
  "Western State",
  "West Virginia",
  "Widener – Delaware",
  "Widener – Commonwealth",
  "Willamette",
  "William and Mary",
  "Wisconsin",
  "Wyoming",
  "Yale",
  "Yeshiva (Cardozo)",
];